ARG NODE_VERSION=17

FROM node:17

WORKDIR /app

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci

USER node

COPY . .

EXPOSE 3000

CMD npm run dev